GET http://localhost:8080/menu
Content-Type: application/json
###
POST http://localhost:8080/menu
Content-Type: application/json

{
  "name": "menu 2",
  "basePrice": 12.0,
  "description": "un menu super",
  "image": "lien vers une image de super menu",
  "productIds": [2]
}
###
DELETE http://localhost:8080/menu
Content-Type: application/json

{
  "id": 2
}
###
PATCH http://localhost:8080/menu
Content-Type: application/json

{
  "id": 2,
  "name": "buerger 11",
  "basePrice": 12.0,
  "description": "un menu burger"
}