GET http://localhost:8080/products
Content-Type: application/json
###
POST http://localhost:8080/product
Content-Type: application/json

{
  "name": "coca",
  "basePrice": 2.0,
  "description": "un coca",
  "image": "lien vers une image de coca",
  "category": "food",
  "available": true
}
###
DELETE http://localhost:8080/product
Content-Type: application/json

{
  "id": 5
}
###
PATCH http://localhost:8080/product
Content-Type: application/json

{
  "id": 11,
  "name": "buerger 11",
  "basePrice": 12.0,
  "description": "un burger",
  "category": "drink",
  "available": false
}