@host=http://localhost:8080

GET {{host}}/status
###
POST http://localhost:8080/employee
Content-Type: application/json

{
  "name": "alice",
  "roles": ["admin", "manager"]
}
###
POST http://localhost:8080/product
Content-Type: application/json

{
  "name": "burger",
  "basePrice": 12.0,
  "description": "un burger",
  "image": "lien vers une image de burger",
  "category": "food"
}