GET http://localhost:8080/status
###
POST http://localhost:8080/employee
Content-Type: application/json

{
  "name": "alice",
  "roles": ["admin", "manager"]
}
###
POST http://localhost:8080/product
Content-Type: application/json

{
  "name": "burgeraaaa",
  "basePrice": 12.0,
  "description": "un burger",
  "image": "lien vers une image de burger",
  "category": "food"
}
###
GET http://localhost:8080/products?page=1
Content-Type: application/json